### ISSUE TITLE
Please make sure the code is up to standards for 2019

### ISSUE THREAD

**Issue by codingjeremy** [android/animation-samples#21]
<a href="https://github.com/EbrahimKaram"><img src="https://avatars2.githubusercontent.com/u/10140799?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [EbrahimKaram](https://github.com/EbrahimKaram)**
_Saturday Apr 13, 2019 at 20:35 GMT_
_Originally opened as https://github.com/googlesamples/android-ActivitySceneTransitionBasic/issues/12_

----

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: Application

**Comment by yaraki** [comment]
Fixed by https://github.com/android/animation-samples/commit/5322faa6a4bd27b39e9074ed2a7868ae99616322
