### ISSUE TITLE
Should ImageFragment check position?

### ISSUE THREAD

**Issue by codingjeremy** [android/animation-samples#24]
<a href="https://github.com/natario1"><img src="https://avatars2.githubusercontent.com/u/15526561?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [natario1](https://github.com/natario1)**
_Saturday Apr 07, 2018 at 16:51 GMT_
_Originally opened as https://github.com/google/android-transition-examples/issues/2_

----

Referring to this:

https://github.com/google/android-transition-examples/blob/6910b1ff673c1abdeff9515d97c41b34f7ee2efc/GridToPager/app/src/main/java/com/google/samples/gridtopager/fragment/ImageFragment.java#L74

I think you should check for position to before calling `startPostponedEnterTransition`, right?
You are assuming that the first `ImageFragment` image to be loaded is the requested one, but that's not so obvious e.g. with network pictures. Correct me if I'm wrong.

**Comment by yaraki** [comment]
You're right. It should check the position.
