### ISSUE TITLE
Square images in grid view

### ISSUE THREAD

**Issue by codingjeremy** [android/animation-samples#25]
<a href="https://github.com/sbakhtiarov"><img src="https://avatars2.githubusercontent.com/u/3224203?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sbakhtiarov](https://github.com/sbakhtiarov)**
_Thursday May 03, 2018 at 07:46 GMT_
_Originally opened as https://github.com/google/android-transition-examples/issues/3_

----

Could you please suggest the way to handle image transformation from a square view (with centerCrop applied) in RecyclerView to a full screen (fitCenter) in the image details fragment?
Once I add the cropping the animations are broken. The image is not scaled correctly and size jumps when it is animated back from full screen.

**Comment by codingjeremy** [comment]
<a href="https://github.com/muthuraj57"><img src="https://avatars1.githubusercontent.com/u/10187654?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [muthuraj57](https://github.com/muthuraj57)**
_Thursday Nov 15, 2018 at 15:52 GMT_

----

Any update? Changing _fitCenter_ to _centerCrop_ in ImageView of **image_card** layout produces broken animation.

**Comment by codingjeremy** [comment]
<a href="https://github.com/frfmmdreza"><img src="https://avatars2.githubusercontent.com/u/47992700?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frfmmdreza](https://github.com/frfmmdreza)**
_Monday Mar 25, 2019 at 21:03 GMT_

----

any update? this is my problem too.

**Comment by codingjeremy** [comment]
<a href="https://github.com/guillaume-tgl"><img src="https://avatars1.githubusercontent.com/u/2244170?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillaume-tgl](https://github.com/guillaume-tgl)**
_Wednesday Mar 27, 2019 at 16:34 GMT_

----

I'm interested in the answer too :)

**Comment by idanbensha** [comment]
Same here. following..

**Comment by yaraki** [comment]
Check out the `Motion` sample. The shared element pattern there demonstrates how to use `centerCrop` scale type and apply `ChangeImageTransform` to animate between different scale types.

**Comment by muthuraj57** [comment]
@yaraki Can you link the repo here? I can't find anything named Motion in github.com/android

**Comment by yaraki** [comment]
It's in this repository here.
https://github.com/android/animation-samples/tree/master/Motion

ChangeImageTransform is used here.
https://github.com/android/animation-samples/blob/master/Motion/app/src/main/java/com/example/android/motion/demo/sharedelement/CheeseDetailFragment.kt
