### ISSUE TITLE
currentFragment.getView() is called before view is created and receiving always null

### ISSUE THREAD

**Issue by codingjeremy** [android/animation-samples#27]
<a href="https://github.com/iAmMONK"><img src="https://avatars0.githubusercontent.com/u/15956050?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iAmMONK](https://github.com/iAmMONK)**
_Tuesday Jun 05, 2018 at 09:37 GMT_
_Originally opened as https://github.com/google/android-transition-examples/issues/6_

----

**Comment by yaraki** [comment]
Can't reproduce.
