### ISSUE TITLE
Shared Transition Listener doesnt give a callback when sceen is locked

### ISSUE THREAD

**Issue by codingjeremy** [android/animation-samples#28]
<a href="https://github.com/Amanr790"><img src="https://avatars0.githubusercontent.com/u/33420830?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Amanr790](https://github.com/Amanr790)**
_Thursday Jul 19, 2018 at 12:11 GMT_
_Originally opened as https://github.com/google/android-transition-examples/issues/7_

----

Hello i have faced an issue where locking the screen just before shared transition doesnt give me a callback.

Thanks and Regards
Aman

**Comment by yaraki** [comment]
Not very relevant to any of the samples
Please create a project reproducing the issue and file it on issuetracker.google.com.
