### ISSUE TITLE
NPE because of android:duration

### ISSUE THREAD

**Issue by codingjeremy** [android/animation-samples#29]
<a href="https://github.com/yallam08"><img src="https://avatars3.githubusercontent.com/u/978690?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yallam08](https://github.com/yallam08)**
_Saturday Dec 08, 2018 at 01:41 GMT_
_Originally opened as https://github.com/google/android-transition-examples/issues/8_

----

The `android:duration` attribute in _image_shared_element_transition.xml_ file causes a NPE

But when it's removed and the duration is set programmatically, it works fine:
`Transition transition = TransitionInflater.from(getContext()).inflateTransition(R.transition.image_shared_element_transition);
transition.setDuration(375);`

**Comment by yaraki** [comment]
Can't reproduce.
